### ISSUE TITLE
Error In Running `npm run dev`

### ISSUE THREAD

**Issue by Bobby3105** [basically-email/Basically.email#2]
I just overwrote my local files with the current commit where I last updated the readme.md file

> 4d76b1d

And I'm receiving an error when trying to run `npm run dev` 

- Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).

Just making an issue cuz @code123841 seems to be busy with exams so for later

**Comment by code123841** [comment]
@Bobby3105  the code is running on yarn try `yarn dev` maybe that should help am kinda stuck in the JSON  unmasehl error i'll create a issue fr it a little later

**Comment by Bobby3105** [comment]
Same error man, lemme post the entire error so you could take a look

Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Could not find files for / in .next/build-manifest.json
Could not find files for / in .next/build-manifest.json
FetchError: request to http://localhost:9000/api/subscribers failed, reason: connect ECONNREFUSED 127.0.0.1:9000
    at ClientRequest.<anonymous> (file:///Users/akshithchowdary/Developer/Coding/Projects/WebDevProjects/basically.email/node_modules/node-fetch/src/index.js:95:11)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.emit (domain.js:470:12)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  erroredSysCall: 'connect'
}

**Comment by code123841** [comment]
Yea mostly looks like an error that i alrdy solved in the previous commit.

**Comment by code123841** [comment]
https://stackoverflow.com/questions/70638408/problem-with-the-unmarshal-error-in-the-api-listmonk
@Bobby3105  If you could Figure it out?

**Comment by Bobby3105** [comment]
> https://stackoverflow.com/questions/70638408/problem-with-the-unmarshal-error-in-the-api-listmonk @Bobby3105 If you could Figure it out?

I can't run the thing lol, I'll try to take a look

**Comment by Bobby3105** [comment]
> Yea mostly looks like an error that i alrdy solved in the previous commit.

Same error after overwriting local and then yarn dev

**Comment by code123841** [comment]
@Bobby3105  did it work? And i found an Solution to the docker compose file too!
I'll create a new issue fr the docker file..

**Comment by Bobby3105** [comment]
Yarn dev still doesn't work, If it has something to do with docker then I get the same db.healthSevices.something has to be a number thing

Don't make a new issue, we'll assume docker is causing the problem and you can put the solution here, if that works then we can close this issue

**Comment by Bobby3105** [comment]
Closing, fixed with removing `retries` from docker-compose.yml file thing and resetting my local repository, to not include `node-fetch`
